version: '3.8'

services:
  web1:
    build: ./web1
    volumes:
      - ./img:/app/img
    expose:
      - "80"

  web2:
    build: ./web2
    volumes:
      - ./img:/app/img
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2